name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=1.24.0
  - scikit-learn=0.24.1
  - python=3.8
  - pip:
      - wandb==0.12.15
      - git+https://github.com/hi9105/Build-ML-Pipeline.git#egg=wandb-utils&subdirectory=components